name: "Load Today's Light Telegram ID!"

on:
  # Run twice per day at 01:35 and 14:35 UTC
  schedule:
    - cron: '35 14 * * *'
    - cron: '35 1 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  load-light-telegram-id:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup gitHub User Details
        uses: octoleo/git-user@v2
        with:
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-user: ${{ secrets.GPG_USER }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-pub: ${{ secrets.SSH_PUB }}
          git-user: ${{ secrets.GIT_USER }}
          git-email: ${{ secrets.GIT_EMAIL }}

      - name: Clone Daily Light Repository
        run: |
          /bin/git clone git@github.com:trueChristian/daily-light.git daily_light

      - name: Build the Daily Scripture Telegram ID
        env:
          BOT_TOKEN: ${{ secrets.DAILY_LIGHT_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.TG_DAILY_LIGHT_GROUP_ID }}
        run: |
          cd daily_light
          /bin/bash ./src/telegram.sh

